### ISSUE TITLE
7.8.3-r1 Settings

### ISSUE THREAD

**Issue by sergtech** [bitnami/bitnami-docker-suitecrm#55]
A. On two existing instances of suiteCRM, running the 7.8.3-r1 stack, attempting to enter the System Settings fails (with a blank page). Rolling back to 7.8.3-r0 and it works without any issues.

B. The About page doesn't show a SuiteCrm version number. (again does in 7.8.3-r0)

C. Upload directory -- the previously raised issue (#46) about the config.php having incorrect xxxxx-upload link appears to be fixed in the sense that a new xxxxx-upload is not created but rather the old one is kept -- this one needs to be explored a bit more.

D. For Invoices and Quotes (and maybe other modules) when editing an existing item, and then saving, it returns to a blank page instead of the Detail View. Again the issue is not present in the 7.8.3-r0 release and disappears when rolling back to it. 
Edit: The issue appears only related to drop-down item change, whether existing (part of default CRM or custom), and is still present in 7.8.3-r2. The change to the invoice/quote is made, and can be seen if reloading the object in another browser tab.

**Comment by andresbono** [comment]
Hello @sergtech. I am able to reproduce the issue. When we fixed #54 we added new directories to persist like the `include` folder and suiteCrm is not able to access to some application files.

We are working on the new revision of the module including the fixes for this issue and #46. In the meantime, you can copy the `includes` directory from `/bitnami/suitecrm` to `/opt/bitnami/suitecrm`. Inside the container run:

```
rm /opt/bitnami/suitecrm/include
cp -r /bitnami/suitecrm/include /opt/bitnami/suitecrm/
```

Thanks again for reporting it.

**Comment by sergtech** [comment]
@andresbono Your solution doesn't appear to work (although there is clearly an issue there)
from apache logs when attempting to open the settings page: 

> [Sat May 06 08:31:37.951021 2017] [:error] [pid 180] [client 10.0.0.142:41152] PHP Warning:  require_once(install/install_utils.php): failed to open stream: No such file or directory in /bitnami/suitecrm/modules/Configurator/Configurator.php on line 186, referer: https://10.0.0.196:13444/index.php?module=Administration&action=index
> [Sat May 06 08:31:37.951099 2017] [:error] [pid 180] [client 10.0.0.142:41152] PHP Fatal error:  require_once(): Failed opening required 'install/install_utils.php' (include_path='/bitnami/suitecrm:/bitnami/suitecrm/include/HTMLPurifier/standalone:/bitnami/suitecrm/include/..:.:/opt/bitnami/php/lib/php') in /bitnami/suitecrm/modules/Configurator/Configurator.php on line 186, referer: https://10.0.0.196:13444/index.php?module=Administration&action=index

> find |grep install_utils
> ./opt/bitnami/suitecrm/install/install_utils.php

The actual solution only to being able to enter the settings page (Point A of the original post)

```
cp -rv /opt/bitnami/suitecrm/install/ /bitnami/suitecrm/
chown -R daemon:daemon /bitnami/suitecrm/install/
```
maybe someone can get this fixed in the image? (since it needs to be re-applied every reboot)

**Comment by dbarranco** [comment]
Hi @sergtech!

I followed the @andresbono solution and I'm able to open this route `index.php?module=Administration&action=index` in the server and nothing new appears on the error log. So I'm not able to reproduce it on the 7.8.1-r1.

While we are working on a new revision of the module we will consider this as well. In the meantine, if that solution is working for you, you could add that commands in the `app-entrypoing.sh` to avoid executing that in each restart.

Thank you so much for reporting it sergtech! 
Best regards

**Comment by sergtech** [comment]
Still experiencing intermittent issues, but it's not a show stopper. 
Seems to happen after container restart, especially if environment is destroyed. 
Sample docker-compose.yml

> version: '2'
> services:
>   mariadb_temptest2CRM:
>     image: 'bitnami/mariadb:latest'
>     volumes:
>       - '/dev/shm/temptest2/mariadb_data:/bitnami/mariadb'
>     environment:
>       - MARIADB_ROOT_PASSWORD=somepassword
>       - "TZ=Australia/Melbourne"
>   suitecrm_temptescrm:
>     image: 'bitnami/suitecrm:7.8.3-r1'
>     ports:
>       - '22223:443'
>     volumes:
>       - '/dev/shm/temptest2/suitecrm_data:/bitnami/suitecrm'
>       - '/dev/shm/temptest2/apache_data:/bitnami/apache'
>       - '/dev/shm/temptest2/php_data:/bitnami/php'
>     environment:
>       - SUITECRM_USERNAME=user
>       - SUITECRM_PASSWORD=password
>       - SUITECRM_EMAIL=someone@test.net
>       - SUITECRM_LASTNAME=TempTestCRM
>       - SUITECRM_HOST=10.0.0.127:22223
>       - MARIADB_HOST=mariadb_temptest2CRM
>       - MARIADB_PASSWORD=somepassword
>       - "TZ=Australia/Melbourne"
> 
>     depends_on:
>       - mariadb_temptest2CRM

then run 

`docker-compose up `

then 

`docker-compose down`
then run some other container (seems to destroy some sort of session data)

then 
`docker-compose up `

Now the settings doesn't work. 
Can't see anything in the log though.
