### ISSUE TITLE
imap.so does not have SSL support (SuiteCRM version 7.8.3)

### ISSUE THREAD

**Issue by trevoriancox** [bitnami/bitnami-docker-suitecrm#75]
**Description**

Unable to use incoming email feature of SuiteCRM 7.8.3 because IMAP connection fails with port 993 configured.
 
**Steps to reproduce the issue:**

Attempt to test email connection with SSL selected in SuiteCRM, or:

`$mbox = imap_open("{imap.gmail.com:993/imap/ssl}", $mail_username, $mail_password)`

**Describe the results you received:**

SuiteCRM shows timeout message after a long time, and doesn't seem to save SSL checkbox setting.

**Describe the results you expected:**

Successful test.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have no problem connecting to this server from the server or container:

`openssl s_client -connect imap.gmail.com:993 -crlf`

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:04:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 43
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.779GiB
Name: ...
ID: ZBJH:UL7C:KWVI:CQZL:NLBI:5SRD:C6MB:KATF:BLDI:CX5S:2TAG:T2MZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

OVH Public Cloud

**Comment by trevoriancox** [comment]
`phpinfo()` reports
`IMAP c-Client Version	2007e`
but does not list SSL Support.

**Comment by tompizmor** [comment]
Hello @trevoriancox,

Could you please let me know the exact docker image tag? There are several revisions for the 7.8.3 version and I think we fixed an IMAP related issue in one of them.

Also, are you sure that your Gmail credentials are correct? I say this because if you have enabled 2-Step Verification in your Gmail account you would need to [create an application specific password for IMAP](https://www.lifewire.com/get-a-password-to-access-gmail-by-pop-imap-2-1171882).

**Comment by tgruenert** [comment]
same behavior for me.

SuiteCRM 7.10.2 

inside bitname docker image from 
https://github.com/bitnami/bitnami-docker-suitecrm
commitID 2966f6f4c53d1f0a32b42496c9b37a67f42ba153

phpInfo() output is
```
...
imap

IMAP c-Client Version => 2007f
...
```

**Comment by tompizmor** [comment]
Hi @tgruenert,

I was able to reproduce the issue. We will check it and try to find the cause.

**Comment by loftux** [comment]
Hi,

This issue seem to be still present in 7.10.7 (debian). Installed as "latest" friday 31 August, 8am CEST (noticed there seem do be a newer "latest", but commits doesn't indicate a fix for this issue).

I get this errror with Gmail imap
```
Mon Sep  3 06:04:13 2018 [631][1][DEBUG] 13: I-E testing string: {imap.gmail.com:993/service=imap/ssl/secure}INBOX
Mon Sep  3 06:04:13 2018 [631][1][WARN] Saving error level. Try to remove the error_reporting() function from your code.
Mon Sep  3 06:04:13 2018 [631][1][WARN] Pop error level. Try to remove the error_reporting() function from your code.
Mon Sep  3 06:04:13 2018 [631][1][WARN] Saving error level. Try to remove the error_reporting() function from your code.
Mon Sep  3 06:04:13 2018 [631][1][WARN] Pop error level. Try to remove the error_reporting() function from your code.
Mon Sep  3 06:04:13 2018 [631][1][WARN] Saving error level. Try to remove the error_reporting() function from your code.
Mon Sep  3 06:04:13 2018 [631][1][WARN] Pop error level. Try to remove the error_reporting() function from your code.
Mon Sep  3 06:04:13 2018 [631][1][DEBUG] 13: I-E failed using [{imap.gmail.com:993/service=imap/ssl/secure}INBOX] - error: Can't open mailbox {imap.gmail.com:993/service=imap/ssl/secure}INBOX: invalid remote specification
Mon Sep  3 06:04:13 2018 [631][1][DEBUG] 13: I-E clearing error and alert stacks.
```
The error seem to indicate that the ssl support is not present: https://stackoverflow.com/questions/6727276/php-imap-open-invalid-remote-specification-when-trying-connect-to-gmail

Also the phpinfo does not show ssl support for imap as previous reporters have indicated.

**Comment by beltran-rubo** [comment]
Correct, the issue is we should enable SSL for the imap extension. We are currently working on it, we will keep you in the loop with the progress of this change.

**Comment by trevoriancox** [comment]
I'm glad this bug report is proving useful for others. We resolved this by not using Docker.

**Comment by beltran-rubo** [comment]
hi @trevoriancox @loftux @tgruenert we have released SuiteCRM 7.10.7-debian-9-r47 with IMAP module with SSL support. Please confirm the issue has been fixed on your side, thanks!

**Comment by loftux** [comment]
I can confirm that this has fixed the issue.
Thanks!
